# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  publish = "build/"
  command = "scripts/build.sh --install-dependencies --prune-tags"

[context.deploy-preview]
  command = "scripts/build.sh --install-dependencies --prune-tags --preview"
