name: Deploy branch

on:
  workflow_dispatch:

jobs:
  deploy:

    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Deploy HEAD
      run: |
        scripts/deploy.sh
