name: Check for local build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install Pipenv
      uses: dschep/install-pipenv-action@v1

    - name: Install dependencies
      run: scripts/install-dependencies.sh

    - name: Build release
      run: scripts/build build settings/release.json

    - name: Save artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build-latest-release.tar.gz
        path: archives/build-latest-release.tar.gz
